
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'AD64EB42868C5F5C62974ABD29EC8A63'
    
_lr_action_items = {'SIFRAO':([1,3,7,8,],[5,-2,-4,-6,]),'$end':([1,2,3,7,8,9,10,],[-3,0,-2,-4,-6,-5,-1,]),'IGUAL':([1,3,7,8,],[6,-2,-4,-6,]),'HASHTAG':([1,3,7,8,10,],[4,-2,-4,-6,4,]),'ELEMENTO':([0,4,5,6,],[3,8,8,3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,6,],[1,10,]),'expression':([0,],[2,]),'factor':([4,5,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term IGUAL term','expression',3,'p_expression_igual','mainContagem.py',16),
  ('term -> ELEMENTO','term',1,'p_expression_nada','mainContagem.py',43),
  ('expression -> term','expression',1,'p_expression_term','mainContagem.py',113),
  ('term -> term HASHTAG factor','term',3,'p_term_hashtag','mainContagem.py',117),
  ('expression -> term SIFRAO factor','expression',3,'p_term_sifrao','mainContagem.py',124),
  ('factor -> ELEMENTO','factor',1,'p_factor_num','mainContagem.py',134),
]
